---
title: "forecasting_election2020"
author: "Alen Mitrovski, Xiaoyan Yang, Matthew Wankiewicz"
date: "November 2nd, 2020"
abstract: |
  | First sentence. Second sentence. Third sentence. Fourth sentence.
  |
  | **Keywords:** Forecasting, US 2020 Election, Trump, Biden;
output:
  bookdown::pdf_document2:
    citation_package: natbib
toc: FALSE
bibliography: references.bib
---

```{r, echo=F, message=F, warning=F}
#install.packages("tidyverse")
library(tidyverse)
```

```{r}
# read in the polling data
polling <- readRDS("polling_data.rds")

# rename columns of polling data to match post-strat
polling <- polling %>% 
  rename(income_group = household_income,
         education_level = education)

# read in post-strat data 
post_strat <- readRDS("census_data.rds")
post_strat <- post_strat %>% 
  filter(race != "two major races", race != "three or more major races")
```

# Introduction

# Data

## Polling

We have used @citeR and @citeTidyverse so far

Data is from @citeIPUMS and from @citeVSG

```{r data, echo=F, message=F, warning=F}

# set up proportions and plots for polling data (variables we focus on)
gender <- polling %>% 
  group_by(sex) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "poll",
         group = "gender") %>% 
  rename(level = sex)

race <- polling %>% 
  group_by(race) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "poll",
         group = "race") %>% 
  rename(level = race)

income <- polling %>% 
  group_by(income_group) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "poll",
         group = "income") %>% 
  drop_na(income_group) %>% 
  rename(level = income_group)

age <- polling %>% 
  group_by(age_groups) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "poll",
         group = "age") %>% 
  rename(level = age_groups)

 statesicp <- polling %>% 
  group_by(stateicp) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "poll",
         group = "state") %>% 
   rename(level = stateicp)

 education <- polling %>% 
  group_by(education_level) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "poll",
         group = "education") %>% 
   rename(level = education_level)

# set up proportions for post-strat data

gender_post <- post_strat %>% 
  group_by(sex) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "post_strat",
         group = "gender") %>% 
  rename(level = sex)

race_post <- post_strat %>% 
  group_by(race) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "post_strat",
         group = "race") %>% 
  rename(level = race)

income_post <- post_strat %>% 
  group_by(income_group) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "post_strat",
         group = "income") %>% 
  rename(level = income_group)

age_post <- post_strat %>% 
  group_by(age_groups) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "post_strat",
         group = "age") %>% 
  rename(level = age_groups)

statesicp_post <- post_strat %>% 
  group_by(stateicp) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "post_strat",
         group = "state") %>% 
  rename(level = stateicp)

education_post <- post_strat %>% 
  group_by(education_level) %>% 
  summarise(n = n()) %>% 
  mutate(pct = n/sum(n), type = "post_strat",
         group = "education") %>% 
  rename(level = education_level)

variables <- rbind(education, education_post,
             age, age_post, gender, gender_post, 
             race, race_post)

variables %>% ggplot(aes(as.factor(level), pct, group=as.factor(type), linetype = as.factor(type))) + 
  geom_line() + facet_wrap(~group, ncol = 4, scales = "free") + 
  theme(axis.text.x = element_text(angle=70, size = 6, hjust = 1)) +
  labs(x = "category", y = "percentage", linetype = "data set")

variables2 <- rbind(income, income_post,
                    statesicp, statesicp_post)
variables2 %>% ggplot(aes(as.factor(level), pct, group=as.factor(type), linetype = as.factor(type))) + 
  geom_line() + facet_wrap(~group, nrow = 2, scales = "free") + 
  theme(axis.text.x = element_text(angle=70, size = 6, hjust = 1)) +
  labs(x = "category", y = "percentage", linetype = "data set")
```


# Model

```{r model, echo = F, message=F, warning=F}
model <- glm(vote_biden ~ sex + age_groups + race +
               stateicp + income_group + education_level, 
             data = polling, family = binomial())
broom::tidy(model)

x <- polling %>% 
  group_by(income_group) %>% 
  summarise(n = n())
y <- post_strat %>% 
  group_by(income_group) %>% 
  summarise(n = n())
```


# Results

```{r}
post_strat$estimate <- 
  model %>% 
  predict(newdata = post_strat)

post_strat %>% 
  mutate(biden_predict_prop = estimate*cell_prop_of_division_total) %>% 
  group_by(stateicp) %>% 
  summarise(biden_predict = sum(biden_predict_prop))

grouped <- post_strat %>% 
  group_by(sex, age_groups, race, income_group, stateicp, education_level) %>% 
  summarise(n = n()) %>% 
  mutate(prop_total = n/sum(n))
```


# Discussion

# References


